### ISSUE TITLE
Page is unviewable due to MASSIVE gifs

### ISSUE THREAD

**Issue by puttehi** [ye-junzhe/BetterNvim#11]
My browser freezes when you scroll to demo gifs. Out of curiosity I checked the source repo and started downloading it as a zip and stopped when the download reached around 300-500 megabytes (!!!)

It might be best to revert #9 and #10 for now to make the page viewable to all.

I'd guess it's good to aim at ~20 megs of total gifs (in total) at max. I wonder if opening this repository on a limited plan just eats most of your monthly cap. Perhaps making them collapsible stops them from loading on page load and makes them on-demand to keep the page size small as well.

Some pointers:
1. Use low frame rates
2. Use low resolutions (maybe 720p/30fps max, less should work fine for README, 480p/60fps perhaps)
3. Don't use gifs, embed videos like mp4 instead. Gifs are a legacy format for tiny memes in the current day and better alternatives exist.

Interesting looking setup otherwise. Would also like to see the examples on a blank background / something less busy / less transparency as it makes the layout quite messy/hard to read in the images while when focusing for a while it actually seems quite clean.

**Comment by ye-junzhe** [comment]
Sorry about this😂, didn't expect this to happen, I'll try to upload mp4 later.
