### ISSUE TITLE
CPP file error

### ISSUE THREAD

**Issue by G23yl** [ye-junzhe/BetterNvim#15]
<img width="411" alt="Snipaste_2024-03-03_00-29-06" src="https://github.com/ye-junzhe/BetterNvim/assets/122905008/0d9613d0-a216-4b73-a53f-0265b31282e9">

When I enter a cpp file, it will show the info?Is there anything wrong?

**Comment by ye-junzhe** [comment]
> <img alt="Snipaste_2024-03-03_00-29-06" width="411" src="https://private-user-images.githubusercontent.com/122905008/309486994-0d9613d0-a216-4b73-a53f-0265b31282e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODc2MzEsIm5iZiI6MTcwOTc4NzMzMSwicGF0aCI6Ii8xMjI5MDUwMDgvMzA5NDg2OTk0LTBkOTYxM2QwLWEyMTYtNGI3My1hNTNmLTAyNjViMzEyODJlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNDU1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDQyNDNlYTgyMmNkYjczMTFjMDM3OGUwNjBiMGJkNWM3MjRiNTRmZDVlOTZiMzRjMmUzMTczMzdlYTAyNDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yl5JlRsCRGCX0DJhQEXarPT2cZ3msuw4cKHatJAp608">
> When I enter a cpp file, it will show the info?Is there anything wrong?

Do you have all the dependencies installed ? -> https://github.com/ye-junzhe/BetterNvim#prerequisites
And make sure you call `:MasonUpdate` or `:MasonInstall cpplint`.
I think for this case you need to check if you have installled python ? -> https://pypi.org/project/cpplint/
Oh and btw what version of neovim you are using ?

**Comment by G23yl** [comment]
Your suggestions are very useful! I later installed the ```cpplint``` then it works!Thanks!

**Comment by ye-junzhe** [comment]
> Your suggestions are very useful! I later installed the `cpplint` then it works!Thanks!

Glad it helped, have fun with this neovim config😄
